export const GET_SITES = 'BACKGROUND:GET_SITES';
export const CREATE_SITE = 'BACKGROUND:CREATE_SITE';
export const DELETE_SITE = 'BACKGROUND:DELETE_SITE';

export const GET_SITE_REPLACES = 'BACKGROUND:GET_SITE_REPLACES';
export const SET_SITE_REPLACES = 'BACKGROUND:SET_SITE_REPLACES';
export const UPDATE_SITE_REPLACES = 'BACKGROUND:UPDATE_SITE_REPLACES';
export const DELETE_SITE_REPLACES = 'BACKGROUND:DELETE_SITE_REPLACES';
