export const INITIALIZE = 'APP@INITIALIZE';

export const CREATE_SITE = 'CREATE_SITE';
export const DELETE_SITE = 'DELETE_SITE';

export const CREATE_REPLACER = 'CREATE_REPLACER';
export const DELETE_REPLACER = 'DELETE_REPLACER';
